# Site settings
title:          Zarina:The Game [DevBlog]
description:    "Developing blog"
baseurl:        "/Zarinadevblog.github.io"
url:            "https://github.com/IlyaKa97/Zarinadevblog.github.io"

# Author
author:
  name:         Zarina:The Game [DevBlog]
  url:          https://github.com/IlyaKa97/Zarinadevblog.github.io
  email:        Zarinathegame@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

theme: jekyll-theme-cayman